# Generated by Django 5.0.2 on 2024-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=120, null=True)),
                ('foto_produto', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('nota', models.IntegerField(null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('categoria', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
