# Generated by Django 5.0.2 on 2024-04-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='product',
            name='descricao',
        ),
        migrations.AddField(
            model_name='product',
            name='categoria',
            field=models.CharField(default='Sem categoria', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='foto_produto',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
