# Generated by Django 5.0.2 on 2024-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_title_product_nome_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nome_produto',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nota',
            field=models.IntegerField(null=True),
        ),
    ]
