# Generated by Django 5.0.2 on 2024-04-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_categoria_alter_product_nome_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='id_produto',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='product',
            table='produto',
        ),
    ]
